server:
  port: 8080
spring:
  freemarker:
    check-template-location: false
    settings:
      classic_compatible: true
  profiles:
    active: prod
  jackson:
    time-zone: GMT+9
  data:
    redis:
      repositories:
        enabled: false
  # Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  redis:
    #Database index
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #Connection timeout
    timeout: 5000

task:
  pool:
    # Core thread pool size
    core-pool-size: 10
    # Maximum number of threads
    max-pool-size: 30
    # Active time
    keep-alive-seconds: 60
    # Queue capacity
    queue-capacity: 50


#Email verification code valid time/minute
code:
  expiration: 5

#Login graphic verification code valid time/minute
loginCode:
  expiration: 2


#Password encrypted transmission, front-end public key encryption, back-end private key decryption
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

smms:
  token: zzGJOTFjdZ6XhsURRlpgY2JPg4jjNehW



xss:
  enabled: true
  excludes: /api/email,/api/app
  urlPatterns: /api/*
