package vn.thuephonghoc.vo;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.NotBlank;
import java.sql.Timestamp;
import java.util.Date;

/**
 * Transaction details should be stored in the database as needed, and stored in the database here for temporary testing only
 */
@Data
public class TradeVo {

    // (Required) Product description
    @NotBlank
    private String body;

    // (Required) Product name
    @NotBlank
    private String subject;

    // (Required) Merchant order number, which should be generated by the background
    @ApiModelProperty(hidden = true)
    private String outTradeNo;

    // (Required) Third-party order number
    @ApiModelProperty(hidden = true)
    private String tradeNo;

    // (required) price
    @NotBlank
    private String totalAmount;

    // Order status, paid, unpaid, void
    @ApiModelProperty(hidden = true)
    private String state;

    // Creation time, needed when storing in the database
    @ApiModelProperty(hidden = true)
    private Timestamp createTime;

    // Void time, needed when storing in the database
    @ApiModelProperty(hidden = true)
    private Date cancelTime;
}

